version: '3.7'
services:
    centos7:
        build:
            context: .
            dockerfile: Dockerfile
        tmpfs:
          - /run
          - /tmp:exec
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro